spring.application.name=miniESB
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_esb
spring.datasource.username=admin_mini_esb
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
